# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-assert_this_and_that}
  s.version = "1.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jake"]
  s.date = %q{2010-10-05}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jake.otherinbox.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/assert_this_and_that.rb",
     "lib/assert_this_and_that/action_controller_extension.rb",
     "lib/assert_this_and_that/action_controller_extension/accessible_via_format.rb",
     "lib/assert_this_and_that/action_controller_extension/accessible_via_protocol.rb",
     "lib/assert_this_and_that/action_controller_extension/accessible_via_user.rb",
     "lib/assert_this_and_that/action_controller_extension/routing.rb",
     "lib/assert_this_and_that/action_controller_extension/test_case.rb",
     "lib/assert_this_and_that/acts_as_list.rb",
     "lib/assert_this_and_that/assertions.rb",
     "lib/assert_this_and_that/associations.rb",
     "lib/assert_this_and_that/attributes.rb",
     "lib/assert_this_and_that/declarative.rb"
  ]
  s.homepage = %q{http://github.com/jakewendt/assert_this_and_that}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ssl_requirement>, [">= 0.1.0"])
    else
      s.add_dependency(%q<ssl_requirement>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<ssl_requirement>, [">= 0.1.0"])
  end
end

